version: "3.8"

services:
  db:
    container_name: toreca-swap-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: torecaswap
      MYSQL_USER: app
      MYSQL_PASSWORD: settlerakihabara0601
      MYSQL_ROOT_PASSWORD: settlerakihabara0601
      MYSQL_ROOT_HOST: '%'
      TZ: UTC
    command: >
      mysqld 
        --character-set-server=utf8mb4 
        --collation-server=utf8mb4_bin 
        --default_authentication_plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - toreca-swap-volume:/var/lib/mysql

volumes:
  toreca-swap-volume:
